title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io
baseurl: "/just-the-docs-experiment"

aux_links:
  GitHub:
    - "https://github.com/dominicprior/dominicprior.github.io"


sass:
  quiet_deps: true
  silence_deprecations:
    - import

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

logo: "/assets/images/peaceful.webp"
favicon_ico: "/assets/images/favicon.ico"
